"""The dependency lock, and the reason it carries more than one hash.

A bare `pip download` takes the wheel that suits the interpreter running
it. That is one artefact per package, so the lock it writes is a lock
for one machine, and the `--require-hashes` install the file's own
header recommends then fails everywhere else. It did: rpds-py was pinned
to a single Windows CPython 3.14 wheel while CI built on four platform
and version pairs.

These tests are offline. The generator reaches the network and is run by
hand; what is held here is the shape of what it writes and the guard
that stops the silent version walk.
"""

import re
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from tools import gen_lock  # noqa: E402

LOCKS = ("tools/requirements.txt", "tools/requirements-dev.txt")

# A package with compiled wheels cannot honestly carry one hash across a
# multi-platform matrix. Naming it keeps the regression specific.
COMPILED = "rpds-py"
PYTHON_311_COMPAT = "typing-extensions"


def _blocks(text):
    """name -> list of digests, parsed from a requirements lock."""
    out = {}
    for block in re.split(r"\n(?=[A-Za-z])", text):
        head = block.split("==")[0].strip()
        if not head or head.startswith("#"):
            continue
        out[head] = re.findall(r"--hash=sha256:([0-9a-f]{64})", block)
    return out


@pytest.mark.parametrize("rel", LOCKS)
def test_lock_is_generated_and_says_what_it_covers(rel):
    text = (REPO / rel).read_text(encoding="utf-8")
    assert text.startswith("# GENERATED by tools/gen_lock.py")
    assert "--require-hashes" in text
    # The platform list is the honest half: a reader on an uncovered
    # platform should learn it here, not from a failed install.
    assert "Platforms covered:" in text
    assert "CPython versions covered:" in text


@pytest.mark.parametrize("rel", LOCKS)
def test_every_pin_carries_at_least_one_hash(rel):
    for name, digests in _blocks((REPO / rel).read_text(encoding="utf-8")).items():
        assert digests, f"{name} in {rel} is pinned with no hash"


@pytest.mark.parametrize("rel", LOCKS)
def test_the_compiled_dependency_carries_a_hash_per_target(rel):
    """One hash here means the lock was regenerated on one machine."""
    digests = _blocks((REPO / rel).read_text(encoding="utf-8")).get(COMPILED)
    assert digests, f"{COMPILED} is absent from {rel}"
    assert len(digests) >= len(gen_lock.TARGETS), (
        f"{COMPILED} carries {len(digests)} hash(es) in {rel} against "
        f"{len(gen_lock.TARGETS)} declared targets, so the lock serves "
        f"fewer platforms than it claims")
    assert len(digests) == len(set(digests)), "duplicate hashes"


def test_targets_cover_what_ci_builds():
    """The lock must serve every job in .github/workflows/checks.yml."""
    ci = (REPO / ".github/workflows/checks.yml").read_text(encoding="utf-8")
    assert "--require-hashes" in ci, (
        "CI installs without the lock, so nothing holds the lock true")
    labels = {label for label, _, _ in gen_lock.TARGETS}
    pythons = {py for _, _, py in gen_lock.TARGETS}
    assert {"linux-x86_64", "windows-amd64"} <= labels
    for version in ("3.11", "3.14"):
        assert version in ci and version in pythons


@pytest.mark.parametrize("label", [
    "linux-x86_64", "windows-amd64", "macos-arm64",
])
def test_python_version_marker_uses_the_declared_target(label):
    requirement = "typing-extensions>=4.4.0; python_version < '3.13'"
    assert gen_lock._active_requirement(requirement, label, "3.11") == (
        "typing-extensions>=4.4.0")
    assert gen_lock._active_requirement(requirement, label, "3.14") is None


@pytest.mark.parametrize("python", ["3.11", "3.14"])
def test_platform_marker_uses_the_declared_target(python):
    requirement = "colorama; sys_platform == 'win32'"
    assert gen_lock._active_requirement(
        requirement, "windows-amd64", python) == "colorama"
    assert gen_lock._active_requirement(
        requirement, "linux-x86_64", python) is None
    assert gen_lock._active_requirement(
        requirement, "macos-arm64", python) is None


def test_unrequested_extra_is_not_in_the_target_closure():
    assert gen_lock._active_requirement(
        "sphinx; extra == 'docs'", "linux-x86_64", "3.11") is None


def test_requested_extra_is_refused_until_its_closure_is_modelled():
    with pytest.raises(SystemExit, match="extras are not supported"):
        gen_lock._active_requirement(
            "jsonschema[format]==4.23.0", "linux-x86_64", "3.11")


def test_patch_sensitive_marker_is_refused_without_a_patch_target():
    with pytest.raises(SystemExit, match="patch-sensitive"):
        gen_lock._active_requirement(
            "compat; python_full_version < '3.11.5'",
            "linux-x86_64", "3.11")


def test_marker_environment_contains_no_host_release_values():
    environment = gen_lock._marker_environment("linux-x86_64", "3.11")
    assert environment["os_name"] == "posix"
    assert environment["platform_machine"] == "x86_64"
    assert environment["platform_release"] == ""
    assert environment["platform_system"] == "Linux"
    assert environment["platform_version"] == ""
    assert environment["sys_platform"] == "linux"
    assert environment["python_version"] == "3.11"


def test_target_resolution_reaches_marker_correct_fixed_point(monkeypatch):
    calls = []

    def download(requirements, _dest, _label, _platforms, _python):
        calls.append(set(requirements))
        artefacts = [Path("root-1.0-py3-none-any.whl")]
        if "typing-extensions>=4.4.0" in requirements:
            artefacts.append(Path("typing_extensions-4.16.0-py3-none-any.whl"))
        # This represents a package pip selected from the host marker
        # environment. It must not seed the declared target's closure.
        artefacts.append(Path("ambient_only-1.0-py3-none-any.whl"))
        return artefacts

    def requirements(path):
        if path.name.startswith("root-"):
            return [
                "typing-extensions>=4.4.0; python_version < '3.13'",
            ]
        if path.name.startswith("ambient_only-"):
            return ["pollution>=1"]
        return []

    monkeypatch.setattr(gen_lock, "_download", download)
    monkeypatch.setattr(gen_lock, "_wheel_requirements", requirements)
    monkeypatch.setattr(gen_lock, "_hash", lambda path: "sha256:" + path.name)

    resolved = gen_lock._resolve_target(
        ["root==1.0"], "linux-x86_64", ["manylinux2014_x86_64"], "3.11")

    assert len(calls) == 2
    assert "typing-extensions>=4.4.0" in calls[-1]
    assert "pollution>=1" not in calls[-1]
    assert set(resolved) == {"root", "typing-extensions"}


def test_download_leaves_dependency_closure_to_the_target_resolver(
        tmp_path, monkeypatch):
    seen = {}

    def run(command, **kwargs):
        seen["command"] = command
        seen["kwargs"] = kwargs
        return SimpleNamespace(returncode=0, stderr="")

    monkeypatch.setattr(gen_lock.subprocess, "run", run)
    assert gen_lock._download(
        {"root==1.0"}, tmp_path, "linux-x86_64",
        ["manylinux2014_x86_64"], "3.11") == []
    assert "--no-deps" in seen["command"]
    assert seen["kwargs"] == {"capture_output": True, "text": True}


@pytest.mark.parametrize("rel", LOCKS)
def test_python_311_compat_dependency_is_hash_locked(rel):
    digests = _blocks((REPO / rel).read_text(encoding="utf-8")).get(
        PYTHON_311_COMPAT)
    assert digests, (
        f"{PYTHON_311_COMPAT} is absent from {rel}; Python 3.11 cannot "
        "install this file with --require-hashes")


@pytest.mark.parametrize("filename,expected", [
    ("rpds_py-2026.6.3-cp314-cp314-win_amd64.whl", ("rpds-py", "2026.6.3")),
    ("attrs-26.1.0-py3-none-any.whl", ("attrs", "26.1.0")),
    ("iniconfig-2.3.0.tar.gz", ("iniconfig", "2.3.0")),
])
def test_artefact_names_parse(filename, expected):
    assert gen_lock._name_version(filename) == expected


def test_an_unparseable_artefact_stops_the_generator():
    with pytest.raises(SystemExit):
        gen_lock._name_version("not-a-wheel")
