"""The dependency lock, and the reason it carries more than one hash.

A bare `pip download` takes the wheel that suits the interpreter running
it. That is one artefact per package, so the lock it writes is a lock
for one machine, and the `--require-hashes` install the file's own
header recommends then fails everywhere else. It did: rpds-py was pinned
to a single Windows CPython 3.14 wheel while CI built on four platform
and version pairs.

These tests are offline. The generator reaches the network and is run by
hand; what is held here is the shape of what it writes and the guard
that stops the silent version walk.
"""

import re
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from tools import gen_lock  # noqa: E402

LOCKS = ("tools/requirements.txt", "tools/requirements-dev.txt")

# A package with compiled wheels cannot honestly carry one hash across a
# multi-platform matrix. Naming it keeps the regression specific.
COMPILED = "rpds-py"


def _blocks(text):
    """name -> list of digests, parsed from a requirements lock."""
    out = {}
    for block in re.split(r"\n(?=[A-Za-z])", text):
        head = block.split("==")[0].strip()
        if not head or head.startswith("#"):
            continue
        out[head] = re.findall(r"--hash=sha256:([0-9a-f]{64})", block)
    return out


@pytest.mark.parametrize("rel", LOCKS)
def test_lock_is_generated_and_says_what_it_covers(rel):
    text = (REPO / rel).read_text(encoding="utf-8")
    assert text.startswith("# GENERATED by tools/gen_lock.py")
    assert "--require-hashes" in text
    # The platform list is the honest half: a reader on an uncovered
    # platform should learn it here, not from a failed install.
    assert "Platforms covered:" in text
    assert "CPython versions covered:" in text


@pytest.mark.parametrize("rel", LOCKS)
def test_every_pin_carries_at_least_one_hash(rel):
    for name, digests in _blocks((REPO / rel).read_text(encoding="utf-8")).items():
        assert digests, f"{name} in {rel} is pinned with no hash"


@pytest.mark.parametrize("rel", LOCKS)
def test_the_compiled_dependency_carries_a_hash_per_target(rel):
    """One hash here means the lock was regenerated on one machine."""
    digests = _blocks((REPO / rel).read_text(encoding="utf-8")).get(COMPILED)
    assert digests, f"{COMPILED} is absent from {rel}"
    assert len(digests) >= len(gen_lock.TARGETS), (
        f"{COMPILED} carries {len(digests)} hash(es) in {rel} against "
        f"{len(gen_lock.TARGETS)} declared targets, so the lock serves "
        f"fewer platforms than it claims")
    assert len(digests) == len(set(digests)), "duplicate hashes"


def test_targets_cover_what_ci_builds():
    """The lock must serve every job in .github/workflows/checks.yml."""
    ci = (REPO / ".github/workflows/checks.yml").read_text(encoding="utf-8")
    assert "--require-hashes" in ci, (
        "CI installs without the lock, so nothing holds the lock true")
    labels = {label for label, _, _ in gen_lock.TARGETS}
    pythons = {py for _, _, py in gen_lock.TARGETS}
    assert {"linux-x86_64", "windows-amd64"} <= labels
    for version in ("3.11", "3.14"):
        assert version in ci and version in pythons


@pytest.mark.parametrize("filename,expected", [
    ("rpds_py-2026.6.3-cp314-cp314-win_amd64.whl", ("rpds-py", "2026.6.3")),
    ("attrs-26.1.0-py3-none-any.whl", ("attrs", "26.1.0")),
    ("iniconfig-2.3.0.tar.gz", ("iniconfig", "2.3.0")),
])
def test_artefact_names_parse(filename, expected):
    assert gen_lock._name_version(filename) == expected


def test_an_unparseable_artefact_stops_the_generator():
    with pytest.raises(SystemExit):
        gen_lock._name_version("not-a-wheel")
