"""Generate hash-locked requirements files from tools/pyproject.toml.

The canonical dependency declaration is tools/pyproject.toml; the
requirements files are GENERATED artefacts and never edited by hand.
pip-tools 7.4/7.5 is incompatible with the installed pip (PackageFinder
API change), so this stdlib generator produces the equivalent lock:
exact pins for the full transitive tree with sha256 hashes, via
pip download + pip hash.

It downloads once per entry in TARGETS and carries every hash it finds,
because a lock with one hash per package is a lock for one machine. The
first version of this generator ran a bare `pip download`, which takes
whatever wheel suits the interpreter running it. That pinned rpds-py to
a single Windows CPython 3.14 wheel, so the `--require-hashes` install
this file's own header recommends failed on three of the four platforms
CI builds on. A compiled package ships one wheel per platform and ABI,
each with its own digest, and `--require-hashes` accepts a requirement
carrying several `--hash` lines and matches the artefact against any of
them. So the fix is to ask for every platform we claim to support and
write all the digests down.

TARGETS covers what CI builds (ubuntu and windows, CPython 3.11 and
3.14) plus the two macOS architectures a developer is likely to be on.
A platform absent from this list is a platform the lock does not serve,
and the generated header says so rather than leaving it to be found at
install time.

Usage: python tools/gen_lock.py
"""

import re
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

TOOLS = Path(__file__).resolve().parent

# (label, [platform tags], python version). Several tags per row because
# a manylinux wheel may be published under any of the tags it satisfies
# and pip matches them literally.
TARGETS = [
    ("linux-x86_64", ["manylinux2014_x86_64", "manylinux_2_17_x86_64",
                      "manylinux_2_28_x86_64"], "3.11"),
    ("linux-x86_64", ["manylinux2014_x86_64", "manylinux_2_17_x86_64",
                      "manylinux_2_28_x86_64"], "3.14"),
    ("windows-amd64", ["win_amd64"], "3.11"),
    ("windows-amd64", ["win_amd64"], "3.14"),
    ("macos-arm64", ["macosx_11_0_arm64"], "3.11"),
    ("macos-arm64", ["macosx_11_0_arm64"], "3.14"),
]

# Intel macOS is deliberately absent. rpds-py stopped publishing an
# x86_64 macOS wheel, so asking for one makes pip walk backwards until
# it finds a version that has one, which is 0.7.1 against the 2026.6.3
# every other target resolves. The version guard below catches that, and
# the honest answer is that this lock does not serve Intel macOS rather
# than that it pins a six-year-old transitive dependency there.

ARTEFACT = re.compile(r"([A-Za-z0-9_.]+)-(\d[^-]*)-")
SDIST = re.compile(r"([A-Za-z0-9_.]+)-(\d[^-]*)\.tar\.gz")


def _pip_version():
    out = subprocess.run(
        [sys.executable, "-m", "pip", "--version"],
        capture_output=True, text=True, check=True).stdout
    return out.split()[1]


HEADER = ("# GENERATED by tools/gen_lock.py from tools/pyproject.toml"
          " using pip {pip}.\n"
          "# Do not edit by hand. Install with:\n"
          "#   python -m pip install --require-hashes -r {name}\n"
          "# Platforms covered: {targets}.\n"
          "# CPython versions covered: {pythons}.\n"
          "# Anything outside those will fail the hash check rather than\n"
          "# install something unpinned.\n")


def _hash(path):
    out = subprocess.run(
        [sys.executable, "-m", "pip", "hash", "--algorithm", "sha256",
         str(path)],
        capture_output=True, text=True, check=True).stdout
    return out.strip().splitlines()[-1].split("--hash=")[-1]


def _name_version(filename):
    m = ARTEFACT.match(filename) or SDIST.match(filename)
    if not m:
        raise SystemExit(f"cannot parse artefact name: {filename}")
    return m.group(1).replace("_", "-").lower(), m.group(2)


def lock(requirements, out_name):
    # name -> version -> set of digests, so a package resolving to two
    # versions across the matrix is visible rather than silently merged.
    found = {}
    for label, platforms, python in TARGETS:
        with tempfile.TemporaryDirectory() as td:
            cmd = [sys.executable, "-m", "pip", "download", "--quiet",
                   "--disable-pip-version-check", "--dest", td,
                   "--only-binary=:all:", "--python-version", python]
            for tag in platforms:
                cmd += ["--platform", tag]
            cmd += list(requirements)
            proc = subprocess.run(cmd, capture_output=True, text=True)
            if proc.returncode != 0:
                raise SystemExit(
                    f"pip download failed for {label} on CPython {python}. "
                    f"Either a dependency publishes no wheel for it, or the "
                    f"target is wrong.\n{proc.stderr.strip()}")
            for artefact in sorted(Path(td).iterdir()):
                name, version = _name_version(artefact.name)
                found.setdefault(name, {}).setdefault(version, set()).add(
                    _hash(artefact))

    split = {n: sorted(v) for n, v in found.items() if len(v) > 1}
    if split:
        raise SystemExit(
            "a package resolved to more than one version across the target "
            "matrix, so one pinned file cannot serve them all: "
            + "; ".join(f"{n} {v}" for n, v in sorted(split.items())))

    rows = []
    for name in sorted(found):
        version, digests = next(iter(found[name].items()))
        lines = " \\\n".join(f"    --hash={d}" for d in sorted(digests))
        rows.append(f"{name}=={version} \\\n{lines}")

    out = TOOLS / out_name
    out.write_text(
        HEADER.format(
            name=f"tools/{out_name}",
            pip=_pip_version(),
            targets=", ".join(sorted({t[0] for t in TARGETS})),
            pythons=", ".join(sorted({t[2] for t in TARGETS})),
        ) + "\n".join(rows) + "\n", encoding="utf-8", newline="\n")
    total = sum(len(d) for v in found.values() for d in v.values())
    print(f"{out_name}: {len(rows)} pinned packages, {total} artefact hashes")


def main():
    data = tomllib.loads((TOOLS / "pyproject.toml").read_text(encoding="utf-8"))
    runtime = data["project"]["dependencies"]
    dev = runtime + data["project"]["optional-dependencies"]["dev"]
    lock(runtime, "requirements.txt")
    lock(dev, "requirements-dev.txt")


if __name__ == "__main__":
    main()
