"""Generate hash-locked requirements files from tools/pyproject.toml.

The canonical dependency declaration is tools/pyproject.toml; the
requirements files are GENERATED artefacts and never edited by hand.
pip-tools 7.4/7.5 is incompatible with the installed pip (PackageFinder
API change), so this stdlib generator produces the equivalent lock:
exact pins for the full transitive tree with sha256 hashes, via
pip download + pip hash.

It resolves once per entry in TARGETS and carries every hash it finds,
because a lock with one hash per package is a lock for one machine. The
first version of this generator ran a bare `pip download`, which takes
whatever wheel suits the interpreter running it. That pinned rpds-py to
a single Windows CPython 3.14 wheel, so the `--require-hashes` install
this file's own header recommends failed on three of the four platforms
CI builds on. A compiled package ships one wheel per platform and ABI,
each with its own digest, and `--require-hashes` accepts a requirement
carrying several `--hash` lines and matches the artefact against any of
them. So the fix is to ask for every platform we claim to support and
write all the digests down.

`pip download --python-version` selects a compatible wheel, but pip
evaluates dependency environment markers against the interpreter running
this generator. A lock generated on Python 3.14 therefore missed
`typing-extensions`, which `referencing` requires on Python 3.11. The
resolver below reads each downloaded wheel's `Requires-Dist` metadata,
evaluates those markers against the declared target and feeds the active
requirements back to pip until the target dependency closure stops moving.

TARGETS covers what CI builds (ubuntu and windows, CPython 3.11 and
3.14) plus the two macOS architectures a developer is likely to be on.
A platform absent from this list is a platform the lock does not serve,
and the generated header says so rather than leaving it to be found at
install time.

Usage: python tools/gen_lock.py
"""

import re
import subprocess
import sys
import tempfile
import tomllib
import zipfile
from email.parser import BytesParser
from pathlib import Path

try:
    from packaging.markers import default_environment
    from packaging.requirements import Requirement
except ImportError:  # pragma: no cover - pip supplies the bootstrap fallback
    from pip._vendor.packaging.markers import default_environment
    from pip._vendor.packaging.requirements import Requirement

TOOLS = Path(__file__).resolve().parent

# (label, [platform tags], python version). Several tags per row because
# a manylinux wheel may be published under any of the tags it satisfies
# and pip matches them literally.
TARGETS = [
    ("linux-x86_64", ["manylinux2014_x86_64", "manylinux_2_17_x86_64",
                      "manylinux_2_28_x86_64"], "3.11"),
    ("linux-x86_64", ["manylinux2014_x86_64", "manylinux_2_17_x86_64",
                      "manylinux_2_28_x86_64"], "3.14"),
    ("windows-amd64", ["win_amd64"], "3.11"),
    ("windows-amd64", ["win_amd64"], "3.14"),
    ("macos-arm64", ["macosx_11_0_arm64"], "3.11"),
    ("macos-arm64", ["macosx_11_0_arm64"], "3.14"),
]

# Intel macOS is deliberately absent. rpds-py stopped publishing an
# x86_64 macOS wheel, so asking for one makes pip walk backwards until
# it finds a version that has one, which is 0.7.1 against the 2026.6.3
# every other target resolves. The version guard below catches that, and
# the honest answer is that this lock does not serve Intel macOS rather
# than that it pins a six-year-old transitive dependency there.

ARTEFACT = re.compile(r"([A-Za-z0-9_.]+)-(\d[^-]*)-")
SDIST = re.compile(r"([A-Za-z0-9_.]+)-(\d[^-]*)\.tar\.gz")

MARKER_PLATFORMS = {
    "linux-x86_64": {
        "os_name": "posix",
        "platform_machine": "x86_64",
        "platform_release": "",
        "platform_system": "Linux",
        "platform_version": "",
        "sys_platform": "linux",
    },
    "windows-amd64": {
        "os_name": "nt",
        "platform_machine": "AMD64",
        "platform_release": "",
        "platform_system": "Windows",
        "platform_version": "",
        "sys_platform": "win32",
    },
    "macos-arm64": {
        "os_name": "posix",
        "platform_machine": "arm64",
        "platform_release": "",
        "platform_system": "Darwin",
        "platform_version": "",
        "sys_platform": "darwin",
    },
}

MAX_CLOSURE_PASSES = 20
PATCH_MARKERS = re.compile(
    r"\b(?:python_full_version|implementation_version)\b")


def _pip_version():
    out = subprocess.run(
        [sys.executable, "-m", "pip", "--version"],
        capture_output=True, text=True, check=True).stdout
    return out.split()[1]


HEADER = ("# GENERATED by tools/gen_lock.py from tools/pyproject.toml"
          " using pip {pip}.\n"
          "# Do not edit by hand. Install with:\n"
          "#   python -m pip install --require-hashes -r {name}\n"
          "# Platforms covered: {targets}.\n"
          "# CPython versions covered: {pythons}.\n"
          "# Anything outside those will fail the hash check rather than\n"
          "# install something unpinned.\n")


def _hash(path):
    out = subprocess.run(
        [sys.executable, "-m", "pip", "hash", "--algorithm", "sha256",
         str(path)],
        capture_output=True, text=True, check=True).stdout
    return out.strip().splitlines()[-1].split("--hash=")[-1]


def _name_version(filename):
    m = ARTEFACT.match(filename) or SDIST.match(filename)
    if not m:
        raise SystemExit(f"cannot parse artefact name: {filename}")
    return _canonical_name(m.group(1)), m.group(2)


def _canonical_name(name):
    return re.sub(r"[-_.]+", "-", name).lower()


def _marker_environment(label, python):
    """Return the PEP 508 environment for one declared lock target."""
    try:
        platform = MARKER_PLATFORMS[label]
    except KeyError as exc:
        raise SystemExit(f"no marker environment for target {label}") from exc
    env = default_environment()
    env.update(platform)
    env.update({
        "implementation_name": "cpython",
        "implementation_version": f"{python}.0",
        "platform_python_implementation": "CPython",
        "python_full_version": f"{python}.0",
        "python_version": python,
        "extra": "",
    })
    return env


def _active_requirement(raw, label, python):
    """Render one requirement without its marker when it applies."""
    requirement = Requirement(raw)
    if requirement.marker:
        marker = str(requirement.marker)
        if PATCH_MARKERS.search(marker):
            raise SystemExit(
                "cannot evaluate a patch-sensitive dependency marker "
                f"against target {python}, which declares no patch version: "
                f"{raw}")
        if not requirement.marker.evaluate(
                environment=_marker_environment(label, python)):
            return None
    if requirement.extras:
        raise SystemExit(
            "dependency extras are not supported by the target marker "
            f"closure: {raw}")
    if requirement.url:
        return f"{requirement.name} @ {requirement.url}"
    return f"{requirement.name}{requirement.specifier}"


def _wheel_requirements(path):
    """Read Requires-Dist rows from a downloaded wheel."""
    if path.suffix != ".whl":
        return []
    with zipfile.ZipFile(path) as wheel:
        metadata = [name for name in wheel.namelist()
                    if name.endswith(".dist-info/METADATA")]
        if len(metadata) != 1:
            raise SystemExit(
                f"expected one METADATA file in {path.name}, found "
                f"{len(metadata)}")
        message = BytesParser().parsebytes(wheel.read(metadata[0]))
    return message.get_all("Requires-Dist") or []


def _download(requirements, dest, label, platforms, python):
    cmd = [sys.executable, "-m", "pip", "download", "--quiet",
           "--disable-pip-version-check", "--dest", str(dest),
           "--only-binary=:all:", "--no-deps",
           "--python-version", python]
    for tag in platforms:
        cmd += ["--platform", tag]
    cmd += sorted(requirements)
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise SystemExit(
            f"pip download failed for {label} on CPython {python}. "
            f"Either a dependency publishes no wheel for it, or the "
            f"target is wrong.\n{proc.stderr.strip()}")
    return sorted(Path(dest).iterdir())


def _resolve_target(requirements, label, platforms, python):
    """Resolve and hash the marker-correct closure for one target."""
    active = {
        rendered
        for raw in requirements
        if (rendered := _active_requirement(raw, label, python))
    }
    if not active:
        return {}
    for _ in range(MAX_CLOSURE_PASSES):
        with tempfile.TemporaryDirectory() as td:
            artefacts = _download(active, td, label, platforms, python)
            active_names = {
                _canonical_name(Requirement(raw).name) for raw in active
            }
            downloaded_names = {
                _name_version(artefact.name)[0] for artefact in artefacts
            }
            missing = active_names - downloaded_names
            if missing:
                raise SystemExit(
                    f"pip omitted active requirements for {label} on "
                    f"CPython {python}: {', '.join(sorted(missing))}")
            discovered = set()
            for artefact in artefacts:
                name, _ = _name_version(artefact.name)
                if name not in active_names:
                    continue
                for raw in _wheel_requirements(artefact):
                    rendered = _active_requirement(raw, label, python)
                    if rendered:
                        discovered.add(rendered)
            if not discovered.issubset(active):
                active.update(discovered)
                continue

            found = {}
            for artefact in artefacts:
                name, version = _name_version(artefact.name)
                # pip may add a dependency selected by the host marker
                # environment. The target closure above decides whether it
                # belongs in this target's lock contribution.
                if name not in active_names:
                    continue
                found.setdefault(name, {}).setdefault(version, set()).add(
                    _hash(artefact))
            return found
    raise SystemExit(
        f"dependency closure did not settle for {label} on CPython {python} "
        f"after {MAX_CLOSURE_PASSES} passes")


def lock(requirements, out_name):
    # name -> version -> set of digests, so a package resolving to two
    # versions across the matrix is visible rather than silently merged.
    found = {}
    for label, platforms, python in TARGETS:
        target = _resolve_target(requirements, label, platforms, python)
        for name, versions in target.items():
            for version, digests in versions.items():
                found.setdefault(name, {}).setdefault(version, set()).update(
                    digests)

    split = {n: sorted(v) for n, v in found.items() if len(v) > 1}
    if split:
        raise SystemExit(
            "a package resolved to more than one version across the target "
            "matrix, so one pinned file cannot serve them all: "
            + "; ".join(f"{n} {v}" for n, v in sorted(split.items())))

    rows = []
    for name in sorted(found):
        version, digests = next(iter(found[name].items()))
        lines = " \\\n".join(f"    --hash={d}" for d in sorted(digests))
        rows.append(f"{name}=={version} \\\n{lines}")

    out = TOOLS / out_name
    out.write_text(
        HEADER.format(
            name=f"tools/{out_name}",
            pip=_pip_version(),
            targets=", ".join(sorted({t[0] for t in TARGETS})),
            pythons=", ".join(sorted({t[2] for t in TARGETS})),
        ) + "\n".join(rows) + "\n", encoding="utf-8", newline="\n")
    total = sum(len(d) for v in found.values() for d in v.values())
    print(f"{out_name}: {len(rows)} pinned packages, {total} artefact hashes")


def main():
    data = tomllib.loads((TOOLS / "pyproject.toml").read_text(encoding="utf-8"))
    runtime = data["project"]["dependencies"]
    dev = runtime + data["project"]["optional-dependencies"]["dev"]
    lock(runtime, "requirements.txt")
    lock(dev, "requirements-dev.txt")


if __name__ == "__main__":
    main()
