"""Generate hash-locked requirements files from tools/pyproject.toml.

The canonical dependency declaration is tools/pyproject.toml; the
requirements files are GENERATED artefacts and never edited by hand.
pip-tools 7.4/7.5 is incompatible with the installed pip (PackageFinder
API change), so this stdlib generator produces the equivalent lock:
exact pins for the full transitive tree with sha256 hashes, via
pip download + pip hash.

Usage: python tools/gen_lock.py
"""

import re
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
def _pip_version():
    out = subprocess.run(
        [sys.executable, "-m", "pip", "--version"],
        capture_output=True, text=True, check=True).stdout
    return out.split()[1]


HEADER = ("# GENERATED by tools/gen_lock.py from tools/pyproject.toml"
          " using pip {pip}.\n"
          "# Do not edit by hand. Install with:\n"
          "#   python -m pip install --require-hashes -r {name}\n")


def lock(requirements, out_name):
    with tempfile.TemporaryDirectory() as td:
        subprocess.run(
            [sys.executable, "-m", "pip", "download", "--quiet",
             "--disable-pip-version-check", "--dest", td, *requirements],
            check=True)
        rows = []
        for wheel in sorted(Path(td).iterdir()):
            m = re.match(r"([A-Za-z0-9_.]+)-(\d[^-]*)-", wheel.name)
            if not m:
                m = re.match(r"([A-Za-z0-9_.]+)-(\d[^-]*)\.tar\.gz",
                             wheel.name)
            if not m:
                raise SystemExit(f"cannot parse artefact name: {wheel.name}")
            name = m.group(1).replace("_", "-").lower()
            version = m.group(2)
            h = subprocess.run(
                [sys.executable, "-m", "pip", "hash", "--algorithm", "sha256",
                 str(wheel)],
                capture_output=True, text=True, check=True).stdout
            digest = h.strip().splitlines()[-1].split("--hash=")[-1]
            rows.append(f"{name}=={version} \\\n    --hash={digest}")
        out = TOOLS / out_name
        out.write_text(HEADER.format(name=f"tools/{out_name}", pip=_pip_version())
                       + "\n".join(rows) + "\n", encoding="utf-8",
                       newline="\n")
        print(f"{out_name}: {len(rows)} pinned artefacts")


def main():
    data = tomllib.loads((TOOLS / "pyproject.toml").read_text(encoding="utf-8"))
    runtime = data["project"]["dependencies"]
    dev = runtime + data["project"]["optional-dependencies"]["dev"]
    lock(runtime, "requirements.txt")
    lock(dev, "requirements-dev.txt")


if __name__ == "__main__":
    main()
